In [1]:
import datetime as dt
import pandas as pd
import numpy as np

In [2]:
avisos = pd.read_csv('/home/luupesado/7506_Datos/2018/TPsDatos_1C2018/TP2/Archivos_a_usar/avisos')

In [5]:
avisos.head()

,Unnamed: 0,idaviso,titulo,descripcion,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa,online
0,0,1111556097,Responsable de Marketing-Producto Div. Constru...,<p>Buscamos un <strong>Responsable de Producto...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Desarrollo de Negocios,Sinteplast S.A.,0.0
1,1,1111949392,Asesor de Servicios - Postventa Chevrolet,"<p><span style="""">Para nuestro cliente, conces...",Gran Buenos Aires,Full-time,Senior / Semi-Senior,Ingeniería Eléctrica y Electrónica,Roycan,1.0
2,2,1112145935,Analistas de Impuestos Sr Ssr y Jr,<p>Importante Estudio de Auditoria y Consultor...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Impuestos,Lighthouse Smart,0.0
3,3,1112146010,Software Engineer,<p> </p><p>Chevron is a multinational company ...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Programación,Chevron Buenos Aires Shared Services Center,1.0
4,4,1112211475,Business Developer Manager,"<p>Importante empresa de energías renovables, ...",Gran Buenos Aires,Full-time,Senior / Semi-Senior,Comercial,RANDSTAD,0.0

In [6]:
del avisos['Unnamed: 0']

In [7]:
avisos['nombre_zona'].value_counts()

Gran Buenos Aires              23011
Capital Federal                 2182
Buenos Aires (fuera de GBA)       57
GBA Oeste                         10
La Plata                           4
Ciudad de Mendoza                  3
Mendoza                            3
Cordoba                            2
Rosario                            2
Santa Cruz                         1
Santa Fe                           1
San Juan                           1
Corrientes                         1
Tucuman                            1
Catamarca                          1
Neuquen                            1
Name: nombre_zona, dtype: int64

In [8]:
def zona_to_num(zona):
    if zona == 'Gran Buenos Aires':
        return 0
    if zona == 'Capital Federal':
        return 1
    else:
        return 2
avisos['nombre_zona'] = avisos['nombre_zona'].map(lambda z: zona_to_num(z))

In [9]:
avisos['tipo_de_trabajo'].value_counts()

Full-time          22827
Part-time           1744
Teletrabajo          248
Por Horas            124
Pasantia             119
Temporario            96
Por Contrato          88
Fines de Semana       28
Primer empleo          6
Voluntario             1
Name: tipo_de_trabajo, dtype: int64

In [10]:
keys = avisos['tipo_de_trabajo'].value_counts().keys()
dict_tipo_to_num = {}
i = 0
for k in keys:
    dict_tipo_to_num[k] = i
    i = i + 1
dict_tipo_to_num

{'Fines de Semana': 7,
 'Full-time': 0,
 'Part-time': 1,
 'Pasantia': 4,
 'Por Contrato': 6,
 'Por Horas': 3,
 'Primer empleo': 8,
 'Teletrabajo': 2,
 'Temporario': 5,
 'Voluntario': 9}

In [12]:
avisos['tipo_de_trabajo'] = avisos['tipo_de_trabajo'].map(lambda t: dict_tipo_to_num[t])

KeyError: 0

In [13]:
avisos['nivel_laboral'].value_counts()

Senior / Semi-Senior                    16977
Junior                                   4149
Otro                                     1971
Jefe / Supervisor / Responsable          1527
Gerencia / Alta Gerencia / Dirección      322
Name: nivel_laboral, dtype: int64

In [14]:
avisos['nivel_laboral'] = avisos['nivel_laboral'].fillna('0')
nivel_to_num = {'Otro': 0,
                'Junior': 1,
                'Senior / Semi-Senior':2,
                'Jefe / Supervisor / Responsable':3,
                'Gerencia / Alta Gerencia / Dirección':4,
                '0' : 0
                }
avisos['nivel_laboral'] = avisos['nivel_laboral'].map(lambda n: nivel_to_num[n])

In [15]:
avisos.head()

,idaviso,titulo,descripcion,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa,online
0,1111556097,Responsable de Marketing-Producto Div. Constru...,<p>Buscamos un <strong>Responsable de Producto...,0,0,2,Desarrollo de Negocios,Sinteplast S.A.,0.0
1,1111949392,Asesor de Servicios - Postventa Chevrolet,"<p><span style="""">Para nuestro cliente, conces...",0,0,2,Ingeniería Eléctrica y Electrónica,Roycan,1.0
2,1112145935,Analistas de Impuestos Sr Ssr y Jr,<p>Importante Estudio de Auditoria y Consultor...,0,0,2,Impuestos,Lighthouse Smart,0.0
3,1112146010,Software Engineer,<p> </p><p>Chevron is a multinational company ...,0,0,2,Programación,Chevron Buenos Aires Shared Services Center,1.0
4,1112211475,Business Developer Manager,"<p>Importante empresa de energías renovables, ...",0,0,2,Comercial,RANDSTAD,0.0

In [16]:
avisos['nombre_area'].value_counts().keys()

Index([u'Ventas', u'Comercial', u'Administración', u'Producción',
       u'Programación', u'Contabilidad', u'Tecnologia / Sistemas',
       u'Atención al Cliente', u'Mantenimiento', u'Recursos Humanos',
       ...
       u'Enfermería (ver Enfermería)', u'Diseño 3D',
       u'Cuidados Intensivos Cardiologicos Adultos', u'Esterilización',
       u'Auditoría de Seguros', u'Fonoaudiología', u'Diagnóstico por imágenes',
       u'Maternidad', u'Farmacia hospitalaria', u'Prácticas cardiológicas'],
      dtype='object', length=188)

In [17]:
keys = avisos['nombre_area'].value_counts().keys()
dict_nombre_area = {}
i = 0
for k in keys:
    dict_nombre_area[k] = i
    i = i + 1
dict_nombre_area

{'Abastecimiento': 44,
 'Administracion de Seguros': 95,
 'Administraci\xc3\xb3n': 2,
 'Administraci\xc3\xb3n de Base de Datos': 104,
 'Administraci\xc3\xb3n de Personal': 20,
 'Almac\xc3\xa9n / Dep\xc3\xb3sito / Expedici\xc3\xb3n': 14,
 'An\xc3\xa1lisis Funcional': 35,
 'An\xc3\xa1lisis de Riesgos': 80,
 'Apoderado Aduanal': 146,
 'Arquitectura': 42,
 'Arte y Cultura': 163,
 'Asesor\xc3\xada Legal Internacional': 158,
 'Asistente': 78,
 'Asistente de Tr\xc3\xa1fico': 107,
 'Atenci\xc3\xb3n al Cliente': 7,
 'Auditor\xc3\xada': 39,
 'Auditor\xc3\xada M\xc3\xa9dica': 155,
 'Auditor\xc3\xada de Seguros': 182,
 'Back Office': 132,
 'Bienestar Estudiantil': 170,
 'Bioquimica': 148,
 'Bioqu\xc3\xadmica': 120,
 'Business Intelligence': 66,
 'Cadeter\xc3\xada': 59,
 'Caja': 102,
 'Calidad': 33,
 'Call Center': 12,
 'Camareros': 55,
 'Capacitaci\xc3\xb3n': 69,
 'Cl\xc3\xadnica M\xc3\xa9dica': 160,
 'Comercial': 1,
 'Comercio Exterior': 114,
 'Community Management': 92,
 'Compensaci\xc3\xb3n y Planilla': 76,
 'Compras': 19,
 'Compras Internacionales/Importaci\xc3\xb3n': 54,
 'Comunicacion': 83,
 'Comunicaciones Externas': 144,
 'Comunicaciones Internas': 141,
 'Construcci\xc3\xb3n': 37,
 'Consultoria': 85,
 'Consultor\xc3\xadas Comercio Exterior': 67,
 'Contabilidad': 5,
 'Control de Gesti\xc3\xb3n': 40,
 'Corporate Finance / Banca Inversi\xc3\xb3n': 108,
 'Creatividad': 138,
 'Cr\xc3\xa9ditos y Cobranzas': 26,
 'Cuentas Corrientes': 90,
 'Cuidados Intensivos Cardiologicos Adultos': 180,
 'Data Entry': 86,
 'Data Warehousing': 150,
 'Desarrollo de Negocios': 32,
 'Diagn\xc3\xb3stico por im\xc3\xa1genes': 184,
 'Direcci\xc3\xb3n': 137,
 'Direcci\xc3\xb3n de Obra': 74,
 'Dise\xc3\xb1o': 111,
 'Dise\xc3\xb1o 3D': 179,
 'Dise\xc3\xb1o Gr\xc3\xa1fico': 73,
 'Dise\xc3\xb1o Industrial': 109,
 'Dise\xc3\xb1o Multimedia': 145,
 'Dise\xc3\xb1o Textil e Indumentaria': 112,
 'Dise\xc3\xb1o Web': 129,
 'Dise\xc3\xb1o de Interiores / Decoraci\xc3\xb3n': 130,
 'Distribuci\xc3\xb3n': 48,
 'E-commerce': 89,
 'Educaci\xc3\xb3n': 106,
 'Educaci\xc3\xb3n especial': 169,
 'Educaci\xc3\xb3n/ Docentes': 87,
 'Emergentolog\xc3\xada': 142,
 'Enfermer\xc3\xada (ver Enfermer\xc3\xada)': 178,
 'Esterilizaci\xc3\xb3n': 181,
 'Est\xc3\xa9tica y Cuidado Personal': 100,
 'Evaluaci\xc3\xb3n Econ\xc3\xb3mica': 119,
 'Exploraci\xc3\xb3n Minera y Petroquimica': 171,
 'Facturaci\xc3\xb3n': 61,
 'Farmacia comercial': 127,
 'Farmacia hospitalaria': 186,
 'Farmacia industrial': 123,
 'Farmac\xc3\xa9utica': 43,
 'Finanzas': 24,
 'Finanzas Internacionales': 151,
 'Fonoaudiolog\xc3\xada': 183,
 'Gastronomia': 11,
 'Gerencia / Direcci\xc3\xb3n General': 58,
 'Hoteler\xc3\xada': 72,
 'Idiomas': 173,
 'Impuestos': 31,
 'Independientes': 143,
 'Infraestructura': 68,
 'Ingenier\xc3\xada  Automotriz': 96,
 'Ingenier\xc3\xada  El\xc3\xa9ctrica y Electr\xc3\xb3nica': 47,
 'Ingenier\xc3\xada  Industrial': 36,
 'Ingenier\xc3\xada  Mec\xc3\xa1nica': 41,
 'Ingenier\xc3\xada  Metalurgica': 118,
 'Ingenier\xc3\xada Agr\xc3\xb3noma': 99,
 'Ingenier\xc3\xada Civil': 64,
 'Ingenier\xc3\xada Electromec\xc3\xa1nica': 77,
 'Ingenier\xc3\xada Geol\xc3\xb3gica': 166,
 'Ingenier\xc3\xada Oficina T\xc3\xa9cnica / Proyecto': 71,
 'Ingenier\xc3\xada Qu\xc3\xadmica': 75,
 'Ingenier\xc3\xada de Procesos': 88,
 'Ingenier\xc3\xada de Producto': 116,
 'Ingenier\xc3\xada de Ventas': 103,
 'Ingenier\xc3\xada en Alimentos': 97,
 'Ingenier\xc3\xada en Minas': 140,
 'Ingenier\xc3\xada en Petr\xc3\xb3leo y Petroqu\xc3\xadmica': 147,
 'Instrumentaci\xc3\xb3n': 154,
 'Instrumentaci\xc3\xb3n Minera': 176,
 'Instrumentaci\xc3\xb3n quir\xc3\xbargica': 175,
 'Internet': 122,
 'Inversiones / Proyectos de Inversi\xc3\xb3n': 117,
 'Investigaci\xc3\xb3n y Desarrollo': 139,
 'J\xc3\xb3venes Profesionales': 49,
 'Kinesiolog\xc3\xada / terapia ocupacional': 162,
 'Laboratorio': 63,
 'Legal': 28,
 'Liderazgo de Proyecto': 53,
 'Log\xc3\xadstica': 10,
 'Mantenimiento': 8,
 'Mantenimiento y Limpieza': 18,
 'Marketing': 16,
 'Maternidad': 185,
 'Media Planning': 115,
 'Medicina': 30,
 'Medicina Laboral': 159,
 'Medio Ambiente': 133,
 'Mercadotecnia Internacional': 174,
 'Mineria/Petroleo/Gas': 62,
 'Multimedia': 156,
 'Negocios Internacionales': 152,
 'Odontolog\xc3\xada': 177,
 'Oficios y Profesiones': 15,
 'Operaciones': 105,
 'Organizaci\xc3\xb3n y M\xc3\xa9todos': 93,
 'Otras Especialidades m\xc3\xa9dicas': 134,
 'Otras Ingenierias': 60,
 'Otras \xc3\xa1reas t\xc3\xa9cnicas en salud': 125,
 'Otros': 23,
 'Pasant\xc3\xada / Trainee': 81,
 'Periodismo': 157,
 'Planeamiento': 121,
 'Planeamiento comercial': 51,
 'Planeamiento econ\xc3\xb3mico-financiero': 98,
 'Producci\xc3\xb3n': 3,
 'Producto': 57,
 'Programaci\xc3\xb3n': 4,
 'Programaci\xc3\xb3n de producci\xc3\xb3n': 50,
 'Promotoras/es': 131,
 'Pr\xc3\xa1cticas Profesionales': 113,
 'Pr\xc3\xa1cticas cardiol\xc3\xb3gicas': 187,
 'Psicolog\xc3\xada': 165,
 'Quimica': 126,
 'Qu\xc3\xadmica': 135,
 'Recepcionista': 17,
 'Recursos Humanos': 9,
 'Redes': 65,
 'Relaciones Institucionales/Publicas': 101,
 'Responsabilidad Social': 149,
 'Salud': 29,
 'Secretaria': 52,
 'Seguridad': 27,
 'Seguridad Industrial': 124,
 'Seguridad Inform\xc3\xa1tica': 94,
 'Seguridad e Higiene': 82,
 'Seguros': 91,
 'Selecci\xc3\xb3n': 34,
 'Servicios': 46,
 'Sistemas': 56,
 'Soporte T\xc3\xa9cnico': 13,
 'Tecnico de Seguros': 136,
 'Tecnologia / Sistemas': 6,
 'Tecnolog\xc3\xadas de la Informaci\xc3\xb3n': 70,
 'Telecomunicaciones': 38,
 'Telefonista': 167,
 'Telemarketing': 22,
 'Tesorer\xc3\xada': 25,
 'Testing / QA / QC': 45,
 'Topograf\xc3\xada': 153,
 'Trabajo Social': 168,
 'Trabajo social': 161,
 'Traduccion': 164,
 'Transporte': 21,
 'Turismo': 79,
 'Urbanismo': 172,
 'Venta de Seguros': 110,
 'Ventas': 0,
 'Ventas Internacionales/Exportaci\xc3\xb3n': 84,
 'Veterinaria': 128}

In [18]:
avisos['nombre_area'] = avisos['nombre_area'].map(lambda n: dict_nombre_area[n])

In [19]:
avisos.head()

,idaviso,titulo,descripcion,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa,online
0,1111556097,Responsable de Marketing-Producto Div. Constru...,<p>Buscamos un <strong>Responsable de Producto...,0,0,2,32,Sinteplast S.A.,0.0
1,1111949392,Asesor de Servicios - Postventa Chevrolet,"<p><span style="""">Para nuestro cliente, conces...",0,0,2,47,Roycan,1.0
2,1112145935,Analistas de Impuestos Sr Ssr y Jr,<p>Importante Estudio de Auditoria y Consultor...,0,0,2,31,Lighthouse Smart,0.0
3,1112146010,Software Engineer,<p> </p><p>Chevron is a multinational company ...,0,0,2,4,Chevron Buenos Aires Shared Services Center,1.0
4,1112211475,Business Developer Manager,"<p>Importante empresa de energías renovables, ...",0,0,2,1,RANDSTAD,0.0

In [20]:
del avisos['titulo']
del avisos['descripcion']
del avisos['denominacion_empresa']

In [21]:
avisos.head()

,idaviso,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,online
0,1111556097,0,0,2,32,0.0
1,1111949392,0,0,2,47,1.0
2,1112145935,0,0,2,31,0.0
3,1112146010,0,0,2,4,1.0
4,1112211475,0,0,2,1,0.0

In [22]:
avisos.to_csv('/home/luupesado/7506_Datos/2018/datos_tp/real_test/TrainingSet/avisos_ts1.csv')